lib/slam_book_web/router.ex
defmodule SlamBookWeb.Router do
  use SlamBookWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SlamBook.Auth, repo: SlamBook.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SlamBookWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/login", SessionController, :new
    get "/logout", SessionController, :delete
    post "/login", SessionController, :create
    resources "/users", UserController do
      resources "/slams", SlamController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SlamBookWeb do
  #   pipe_through :api
  # end
end

lib/slam_book_web/views/layout_view.ex
defmodule SlamBookWeb.LayoutView do
  use SlamBookWeb, :view
end

lib/slam_book_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Slam 2020</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">

            <%= if @current_user do %>
            <%= link "#{@current_user.name}", to: Routes.user_path(@conn, :show, @current_user), class: "shorter-link" %>

            <%= link "See your Slams", to: Routes.user_slam_path(@conn, :index, @current_user), class: "shorter-link" %>

            <%= link "Logout", to: Routes.session_path(@conn, :delete), class: "shorter-link" %>

            <% else %>

            <%= link "Login", to: Routes.session_path(@conn, :new), class: "shorter-link" %>

            <%= link "New User", to: Routes.user_path(@conn, :new), class: "shorter-link" %>
            <% end %>
        </nav>
          <img src="<%= Routes.static_path(@conn, "/images/slam.jpg") %>" alt="Phoenix Framework Logo"/>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>